FROM dronehippie/base:arm64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Buildx" \
  org.opencontainers.image.vendor="Webhippie" \
  org.opencontainers.image.documentation="https://dronehippie.github.io/codacy/"

ENTRYPOINT ["/bin/drone-codacy"]
ADD bin/drone-codacy /bin/
